### ISSUE TITLE
Seems there a crash problem with the flower sack, putting the stack trace from my crash below.

### ISSUE THREAD

**Issue by thenewjonathan** [AllTheMods/ATM-4#103]
This happened when I was trying to add the orange flower into the sack. Light blue, blue, gray and cyan all went in fine, then orange crashed the game. 

Description: handleMouseClick() threw an exception when called from MouseTweaks.

java.lang.reflect.InvocationTargetException: null
	at sun.reflect.GeneratedMethodAccessor19.invoke(Unknown Source) ~[?:?] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at yalter.mousetweaks.handlers.GuiContainerHandler.clickSlot(GuiContainerHandler.java:82) ~[?:2.13] {re:classloading}
	at yalter.mousetweaks.Main.onMouseDrag(Main.java:242) ~[?:2.13] {re:classloading}
	at yalter.mousetweaks.forge.MouseTweaksForge.onGuiMouseDragPre(MouseTweaksForge.java:79) ~[?:2.13] {re:classloading}
	at net.minecraftforge.eventbus.ASMEventHandler_43_MouseTweaksForge_onGuiMouseDragPre_Pre.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:80) ~[eventbus-1.0.0-service.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258) ~[eventbus-1.0.0-service.jar:?] {}
	at net.minecraftforge.client.ForgeHooksClient.onGuiMouseDragPre(ForgeHooksClient.java:952) ~[?:?] {re:classloading}
	at net.minecraft.client.MouseHelper.lambda$cursorPosCallback$3(MouseHelper.java:179) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.MouseHelper$$Lambda$10785/1870316845.run(Unknown Source) ~[?:?] {}
	at net.minecraft.client.gui.screen.Screen.wrapScreenError(Screen.java:441) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.MouseHelper.func_198022_b(MouseHelper.java:178) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.MouseHelper$$Lambda$6190/1145579380.invoke(Unknown Source) ~[?:?] {}
	at org.lwjgl.glfw.GLFWCursorPosCallbackI.callback(GLFWCursorPosCallbackI.java:37) ~[lwjgl-glfw-3.2.2.jar:build 10] {}
	at org.lwjgl.system.JNI.invokeV(Native Method) ~[lwjgl-3.2.2.jar:build 10] {}
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3101) ~[lwjgl-glfw-3.2.2.jar:build 10] {}
	at net.minecraft.client.MainWindow.func_216528_l(SourceFile:408) ~[?:?] {re:classloading,xf:fml:randompatches:RandomPatches MainWindow Transformer}
	at net.minecraft.client.MainWindow.func_198086_a(SourceFile:279) ~[?:?] {re:classloading,xf:fml:randompatches:RandomPatches MainWindow Transformer}
	at net.minecraft.client.Minecraft.func_213227_b(Minecraft.java:947) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:fml:randompatches:RandomPatches Minecraft Transformer,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:911) [?:?] {re:classloading,pl:accesstransformer:B,xf:fml:randompatches:RandomPatches Minecraft Transformer,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:384) [?:?] {re:classloading,pl:accesstransformer:B,xf:fml:randompatches:RandomPatches Minecraft Transformer,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(SourceFile:155) [?:?] {re:classloading}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:56) [forge-1.14.4-28.1.109.jar:28.1] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$399/772791273.call(Unknown Source) [forge-1.14.4-28.1.109.jar:28.1] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-4.1.0.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-4.1.0.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-4.1.0.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81) [modlauncher-4.1.0.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-4.1.0.jar:?] {}
Caused by: java.lang.ArrayIndexOutOfBoundsException: -1
	at java.util.ArrayList.elementData(ArrayList.java:418) ~[?:1.8.0_51] {}
	at java.util.ArrayList.get(ArrayList.java:431) ~[?:1.8.0_51] {}
	at vazkii.botania.client.gui.bag.ContainerFlowerBag.func_82846_b(ContainerFlowerBag.java:91) ~[?:r1.11-372] {re:classloading}
	at net.minecraft.inventory.container.Container.func_184996_a(Container.java:231) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.client.multiplayer.PlayerController.func_187098_a(PlayerController.java:367) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.screen.inventory.ContainerScreen.func_184098_a(ContainerScreen.java:515) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	... 35 more

**Comment by Asshall** [comment]
I don't know much about these mods inner workings but it seems to be an incompatibility  with mouse tweaks. Does it only crash when shift + mouse dragging over multiple flowers ? 
I think you should move the issue to botania's github, but I don't think it would be the author's priority to fix that. 
By just shift + left clicking the flowers one by one it works just fine ;)
