### ISSUE TITLE
Crash Fertilized Farmland

### ISSUE THREAD

**Issue by serioux1337** [AllTheMods/ATM-4#106]
When an inferium seed is planted on normal farmland (hoe on dirt) and then use Red Fertilizer on the farmland, the game crashes.

**Comment by serioux1337** [comment]
Also crashes when use of Red Fertilizer on dirt

---- Minecraft Crash Report ----
// Shall we play a game?

Time: 1/1/20 11:43 PM
Description: Unexpected error

java.lang.IllegalArgumentException: Cannot get property IntegerProperty{name=moisture, clazz=class java.lang.Integer, values=[0, 1, 2, 3, 4, 5, 6, 7]} as it does not exist in Block{minecraft:dirt}
	at net.minecraft.state.StateHolder.func_177229_b(SourceFile:95) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.blay09.mods.farmingforblockheads.item.FertilizerItem$FertilizerType.applyFertilizer(FertilizerItem.java:33) ~[?:5.2.3] {re:classloading}
	at net.blay09.mods.farmingforblockheads.item.FertilizerItem.func_195939_a(FertilizerItem.java:110) ~[?:5.2.3] {re:classloading}
	at net.minecraft.item.ItemStack.lambda$onItemUse$0(ItemStack.java:163) ~[?:?] {re:classloading,xf:fml:quark:add-spacing-for-stack}
	at net.minecraft.item.ItemStack$$Lambda$11039/1727341538.apply(Unknown Source) ~[?:?] {}
	at net.minecraft.item.ItemStack.onItemUse(ItemStack.java:178) ~[?:?] {re:classloading,xf:fml:quark:add-spacing-for-stack}
	at net.minecraft.item.ItemStack.func_196084_a(ItemStack.java:163) ~[?:?] {re:classloading,xf:fml:quark:add-spacing-for-stack}
	at net.minecraft.client.multiplayer.PlayerController.func_217292_a(PlayerController.java:295) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1236) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:fml:randompatches:RandomPatches Minecraft Transformer,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_184117_aA(Minecraft.java:1488) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:fml:randompatches:RandomPatches Minecraft Transformer,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1321) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:fml:randompatches:RandomPatches Minecraft Transformer,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:869) [?:?] {re:classloading,pl:accesstransformer:B,xf:fml:randompatches:RandomPatches Minecraft Transformer,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:384) [?:?] {re:classloading,pl:accesstransformer:B,xf:fml:randompatches:RandomPatches Minecraft Transformer,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(SourceFile:155) [?:?] {re:classloading}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:56) [forge-1.14.4-28.1.109.jar:28.1] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$407/379833480.call(Unknown Source) [forge-1.14.4-28.1.109.jar:28.1] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-4.1.0.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-4.1.0.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-4.1.0.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81) [modlauncher-4.1.0.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-4.1.0.jar:?] {}


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.minecraft.state.StateHolder.func_177229_b(SourceFile:95)
	at net.blay09.mods.farmingforblockheads.item.FertilizerItem$FertilizerType.applyFertilizer(FertilizerItem.java:33)
	at net.blay09.mods.farmingforblockheads.item.FertilizerItem.func_195939_a(FertilizerItem.java:110)
	at net.minecraft.item.ItemStack.lambda$onItemUse$0(ItemStack.java:163)
	at net.minecraft.item.ItemStack$$Lambda$11039/1727341538.apply(Unknown Source)
	at net.minecraft.item.ItemStack.onItemUse(ItemStack.java:178)
	at net.minecraft.item.ItemStack.func_196084_a(ItemStack.java:163)
	at net.minecraft.client.multiplayer.PlayerController.func_217292_a(PlayerController.java:295)
	at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1236)
	at net.minecraft.client.Minecraft.func_184117_aA(Minecraft.java:1488)

-- Affected level --
Details:
	All players: 1 total; [ClientPlayerEntity['Siberia80'/189, l='MpServer', x=194.17, y=78.00, z=472.18]]
	Chunk stats: Client Chunk Cache: 529, 347
	Level dimension: DimensionType{minecraft:overworld}
	Level name: MpServer
	Level seed: 0
	Level generator: ID 07 - biomesoplenty, ver 0. Features enabled: false
	Level generator options: {}
	Level spawn location: World: (208,65,240), Chunk: (at 0,4,0 in 13,15; contains blocks 208,0,240 to 223,255,255), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 3465367 game time, 4120163 day time
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Server brand: forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.world.ClientWorld.func_72914_a(ClientWorld.java:410)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:1750)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:405)
	at net.minecraft.client.main.Main.main(SourceFile:155)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:56)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$407/379833480.call(Unknown Source)
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81)
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65)

-- System Details --
Details:
	Minecraft Version: 1.14.4
	Minecraft Version ID: 1.14.4
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 110308024 bytes (105 MB) / 2036858880 bytes (1942 MB) up to 3008888832 bytes (2869 MB)
	CPUs: 16
	JVM Flags: 5 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx3228m -Xms256m -XX:PermSize=256m
	ModLauncher: 4.1.0+62+5bfa59b
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/eventbus-1.0.0-service.jar eventbus PLUGINSERVICE 
		/forge-1.14.4-28.1.109.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.14.4-28.1.109.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-1.0.1-milestone.0.1+94458e7-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.14.4-28.1.109.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.14.4-28.1.109.jar runtimedistcleaner PLUGINSERVICE 
		/forge-1.14.4-28.1.109.jar fml TRANSFORMATIONSERVICE 
	FML: 28.1
	Forge: net.minecraftforge:28.1.109
	FML Language Providers: 
		javafml@28.1
		minecraft@1
	Mod List: 
		CyclopsCore-1.14.4-1.6.1.jar Cyclops Core {cyclopscore@1.6.1 DONE}
		planttech2-0.01.06.jar PlantTech 2 {planttech2@0.01.06 DONE}
		SilentMechanisms-1.14.4-0.6.9+42.jar Silent's Mechanisms {silents_mechanisms@0.6.9+42 DONE}
		bambooeverything-1.14-1.5.0.jar Bamboo Everything {bambooeverything@1.14-1.5.0 DONE}
		modnametooltip_1.14.3-1.12.1.jar Mod Name Tooltip {modnametooltip@1.12.1 DONE}
		KleeSlabs_1.14.4-7.4.7.jar KleeSlabs {kleeslabs@7.4.7 DONE}
		IronJetpacks-1.14.4-2.0.3.jar Iron Jetpacks {ironjetpacks@2.0.3 DONE}
		xnet-1.14-1.8.7-alpha.jar XNet {xnet@1.14-1.8.7-alpha DONE}
		XaerosWorldMap_1.5.2_Forge_1.14.4.jar Xaero's World Map {xaeroworldmap@1.5.2 DONE}
		CookingForBlockheads_1.14.4-7.4.1.jar Cooking for Blockheads {cookingforblockheads@7.4.1 DONE}
		Controlling-5.0.4.jar Controlling {controlling@5.0.4 DONE}
		Placebo-1.14.4-2.3.5.jar Placebo {placebo@2.3.5 DONE}
		rangedpumps-0.6.1.jar Ranged Pumps {rangedpumps@0.6.1 DONE}
		Fence Jumper-1.14.4-1.0.8.jar FenceJumper {fencejumper@version DONE}
		Bookshelf-1.14.4-4.4.72.jar Bookshelf {bookshelf@4.4.72 DONE}
		randompatches-1.14.4-1.19.1.1.jar RandomPatches {randompatches@1.14.4-1.19.1.1 DONE}
		buildinggadgets-3.1.1b.jar Building Gadgets {buildinggadgets@3.1.1b DONE}
		DarkUtilities-1.14.4-2.0.10.jar Dark Utilities {darkutils@2.0.10 DONE}
		Apotheosis-1.14.4-2.4.4.jar Apotheosis {apotheosis@2.4.4 DONE}
		Morpheus-1.14.4-4.2.44.jar Morpheus {morpheus@version DONE}
		WaterStrainer-1.14.4-7.0.2.jar Water Strainer {waterstrainer@1.14.4-7.0.2 DONE}
		inventorygenerators-1.14.4-1.0.1.jar Inventory Generators {inventorygenerators@1.14.4-1.0.1 DONE}
		TMechworks-1.14.4-2.0.1.jar Tinkers' Mechworks {tmechworks@2.0.1 DONE}
		JustEnoughResources-1.14.4-0.10.0.66.jar Just Enough Resources {jeresources@0.10.0.66 DONE}
		BetterThanMending-1.3.2.jar BetterThanMending {betterthanmending@1.3.2 DONE}
		mysticallib-1.14.4-1.10.0.jar Mystical Lib {mysticallib@1.14.4-1.10.0 DONE}
		refinedstorage-1.7.1.jar Refined Storage {refinedstorage@1.7.1 DONE}
		industrial-foregoing-1.14.4-2.1.2-582ea8b.jar Industrial Foregoing {industrialforegoing@2.1.2 DONE}
		torchmaster-2.0.0-rc2.jar Torchmaster {torchmaster@2.0.0-rc2 DONE}
		BiomesOPlenty-1.14.4-9.0.0.262-universal.jar Biomes O' Plenty {biomesoplenty@1.14.4-9.0.0.259 DONE}
		valkyrielib-3.0.0.8.jar ValkyrieLib {valkyrielib@3.0.0.8 DONE}
		LLOverlayReloaded-1.2.4-mc1.14.4.jar Light Level Overlay Reloaded {llor@1.2.4-mc1.14.4 DONE}
		fairylights-2.1.14-1.14.4.jar Fairy Lights {fairylights@2.1.14 DONE}
		SolarFluxReborn-1.14.4-14.1.3.jar Solar Flux Reborn {solarflux@14.1.3 DONE}
		portality-1.14.4-2.0.4-b0b3467.jar Portality {portality@2.0.4 DONE}
		curios-FORGE-1.14.4-1.0.6.jar Curios API {curios@FORGE-1.14.4-1.0.6 DONE}
		Botania r1.11-372.jar Botania {botania@r1.11-372 DONE}
		Patchouli-1.1-22.jar Patchouli {patchouli@1.1-22 DONE}
		AutoRegLib-1.4-35.jar AutoRegLib {arl@1.4-35 DONE}
		RandomThings-MC1.14.4-5.0.1.jar Random Things {randomthings@5.0.1 DONE}
		BetterThanLlamas-1.14.4-1.1.0.jar Better Than Llamas {betterthanllamas@1.1.0 DONE}
		OreExcavation-1.6.145.jar Ore Excavation {oreexcavation@1.6.145 DONE}
		elevatorid-1.14.4-1.5.2.jar Elevator Mod {elevatorid@1.14.4-1.5.2 DONE}
		tombstone-4.1.8-1.14.4.jar Corail Tombstone {tombstone@4.1.8 DONE}
		cc-tweaked-1.14.4-1.86.0.jar CC: Tweaked {computercraft@1.86.0 DONE}
		AI-Improvements-1.14.4-0.3.0.jar AI-Improvements {aiimprovements@0.2.2 DONE}
		tramplestopper-1.14.4-2.0.0.26-universal.jar Trample Stopper {tramplestopper@1.14.4-2.0.0.26-universal DONE}
		YAMDA-4.1.1.jar YAMDA {yamda@4.1.1 DONE}
		StevesFactoryManager-1.14.4-3.0.0-alpha23.jar Steve's Factory Manager {sfm@1.14.4-3.0.0-alpha DONE}
		rockcandy-1.14.4-1.1.6.jar Rock Candy {rockcandy@version DONE}
		Cyclic-1.14.4-0.0.12.jar Cyclic {cyclic@1.14.4-0.0.12 DONE}
		dwarfcoal-1.14.4-1.0.0.jar Dwarf Coal {dwarfcoal@1.14.3-1.1.0 DONE}
		inventorysorter-1.14.4-16.2.0.jar Simple Inventory Sorter {inventorysorter@16.2.0 DONE}
		Cucumber-1.14.4-2.0.6.jar Cucumber Library {cucumber@2.0.6 DONE}
		BetterThanBunnies-1.14.4-1.2.0.jar Better Than Bunnies {betterthanbunnies@1.2.0 DONE}
		jei-1.14.4-6.0.0.27.jar Just Enough Items {jei@6.0.0.27 DONE}
		metalbarrels-1.4.jar Metal Barrels {metalbarrels@1.4 DONE}
		Druidcraft-1.14-0.2.32.jar Druidcraft {druidcraft@0.2.32 DONE}
		ensorcellation-1.14.4-0.2.0b.jar Ensorcellation {ensorcellation@0.2.0b DONE}
		enviromats-2.0.0.9.jar Environmental Materials {enviromats@2.0.0.9 DONE}
		comforts-FORGE-1.14.4-2.0-beta4.jar Comforts {comforts@FORGE-1.14.4-2.0-beta4 DONE}
		EnderBags-1.14.4-4.2.0.jar Ender Bags {ender_bags@4.2.0 DONE}
		SimpleStorageNetwork-1.14.4-0.2.0.jar Simple Storage Network {storagenetwork@1.14.4-0.2.0 DONE}
		FarmingForBlockheads_1.14.4-5.2.3.jar Farming for Blockheads {farmingforblockheads@5.2.3 DONE}
		cofh_core-1.14.4-0.2.0b.jar CoFH Core {cofh_core@0.2.0b DONE}
		mcjtylib-1.14-3.5.17-alpha.jar McJtyLib {mcjtylib@1.14-3.5.17-alpha DONE}
		rftoolsbase-1.14-0.0.12-alpha.jar RFToolsBase {rftoolsbase@1.14-0.0.12-alpha DONE}
		rftoolsstorage-1.14-0.0.7-alpha.jar RFToolsStorage {rftoolsstorage@1.14-0.0.7-alpha DONE}
		restrictions-1.14-1.3.10.jar Restrictions {restrictions@1.14-1.3.10 DONE}
		ClickMachine-1.14.4-2.1.2.jar Click Machine {clickmachine@2.1.2 DONE}
		ToastControl-1.14.4-2.2.0.jar Toast Control {toastcontrol@2.2.0 DONE}
		PackingTape-1.14.4-0.9.0.jar Packing Tape {packingtape@0.9.0 DONE}
		mininggadgets-1.2.3.jar Mining Gadgets {mininggadgets@1.2.3 DONE}
		CraftTweaker-1.14.4-5.0.1.150.jar CraftTweaker {crafttweaker@5.0.1.150 DONE}
		rftoolspower-1.14-1.2.12-alpha.jar RFToolsPower {rftoolspower@1.14-1.2.12-alpha DONE}
		mysticalworld-1.14.4-1.6.12.jar Mystical World {mysticalworld@1.14.4-1.6.12 DONE}
		forge-1.14.4-28.1.109-universal.jar Forge {forge@28.1.109 DONE}
		QuickLeafDecay-MC1.14.4-1.2.5.jar Quick Leaf Decay {quickleafdecay@1.2.5 DONE}
		ColossalChests-1.14.4-1.7.6.jar ColossalChests {colossalchests@1.7.6 DONE}
		MysticalAgriculture-1.14.4-2.0.4.jar Mystical Agriculture {mysticalagriculture@2.0.4 DONE}
		ironchest-1.14.4-9.1.5.jar Iron Chests {ironchest@1.14.3-9.0.3 DONE}
		CraftingTweaks_1.14.4-10.1.4.jar Crafting Tweaks {craftingtweaks@10.1.4 DONE}
		forge-1.14.4-28.1.109-client.jar Minecraft {minecraft@1.14.4 DONE}
		rftoolsutility-1.14-1.2.13-alpha.jar RFToolsUtility {rftoolsutility@1.14-1.2.13-alpha DONE}
		Flopper-1.14.4-1.0.5.jar Flopper {flopper@1.0.5 DONE}
		theoneprobe-1.14-1.4.37.jar The One Probe {theoneprobe@NONE DONE}
		swingthroughgrass-1.14.4-1.3.2.jar SwingThroughGrass {swingthroughgrass@1.14.4-1.3.2 DONE}
		MouseTweaks-2.13-mc1.14.4.jar Mouse Tweaks {mousetweaks@2.13 DONE}
		titanium-1.14.4-2.2.10.jar Titanium {titanium@2.2.10 DONE}
		SilentLib-1.14.4-4.4.0+44.jar Silent Lib {silentlib@4.4.0+44 DONE}
		bluepower-1.14.4-0.3.172-alpha-universal.jar Blue Power {bluepower@0.3.172-alpha DONE}
		forbidden_arcanus-1.14.4-1.5-beta-3.jar Forbidden & Arcanus {forbidden_arcanus@1.14.4-1.5-beta-3 DONE}
		archers_paradox-1.14.4-0.1.0a.jar Archer's Paradox {archers_paradox@0.1.0b DONE}
		Ding-1.14.4-1.1.0.jar Ding {ding@1.1.0 DONE}
		rftoolsbuilder-1.14-1.2.12-alpha.jar RFToolsBuilder {rftoolsbuilder@1.14-1.2.12-alpha DONE}
		Quark-r2.0-204.jar Quark {quark@r2.0-204 DONE}
		Mantle-1.14.4-1.4.32.jar Mantle {mantle@1.4.32 DONE}
		Xaeros_Minimap_1.19.4_Forge_1.14.4.jar Xaero's Minimap {xaerominimap@1.19.4 DONE}
		JAOPCA-1.14.4-3.0.0.12.jar JAOPCA {jaopca@3.0.0.12 DONE}
		FastWorkbench-1.14.4-2.1.4.jar FastWorkbench {fastbench@2.1.4 DONE}
		StorageDrawers-1.14.4-6.0.5.jar Storage Drawers {storagedrawers@1.14.4-6.0.3 DONE}
		Harvest-forge-1.14.4-1.2.10-23.jar Harvest {harvest@version DONE}
		Dirt2Path-1.0.0.jar Dirt2Path {d2p@1.0.0 DONE}
		FastFurnace-1.14.4-2.2.4.jar FastFurnace {fastfurnace@2.2.4 DONE}
		AppleSkin-mc1.14.4-forge-1.0.13.jar AppleSkin {appleskin@1.0.13 DONE}
		RefinedRelocation_1.14.4-6.2.4.jar Refined Relocation {refinedrelocation@6.2.4 DONE}
		Aquaculture-1.14.4-2.0.3.jar Aquaculture 2 {aquaculture@1.14.4-2.0.3 DONE}
		XL-Food-Mod-1.14.4-2.1.1.jar XL Food Mod {xlfoodmod@2.1.1 DONE}
		refinedstorageaddons-0.5.jar Refined Storage Addons {refinedstorageaddons@0.5 DONE}
		Ma-Essentials-1.14.4-1.2.8.jar Ma Essentials {ma-essentials@1.14.4-1.2.8 DONE}
		CosmeticArmorReworked-1.14.4-v1a.jar CosmeticArmorReworked {cosmeticarmorreworked@1.14.4-v1a DONE}
		DefaultOptions_1.14.4-10.2.6.jar Default Options {defaultoptions@10.2.6 DONE}
	Launched Version: forge-28.1.109
	LWJGL: 3.2.2 build 10
	OpenGL: Radeon RX 580 Series GL version 4.6.13547 Compatibility Profile Context 25.20.15031.1000, ATI Technologies Inc.
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	CPU: 16x AMD Ryzen 7 1700X Eight-Core Processor

**Comment by HamzaYazaw** [comment]
@serioux1337 
Okay so basically, what I did is

- Put down the dirt
- Used Red Fertilizer on it first, 
- Then you can put down the Inferium seed

works perfectly fine! 
I think it crashes because when you add the fertilizer on the seed, it won't be able to use on it. So it only works on dirt. 
Will definitely crash when you add the fertilizer on anything else
